### ISSUE TITLE
Merge with `ember-cli-deploy-build`

### ISSUE THREAD

**Issue by sandstrom** [martinic/ember-cli-deploy-build-plus#225]
Would it be possible to merge the functionality of this plugin with `ember-cli-deploy-build`. It's quite confusing as a user with two plugins doing (to my eyes) more or less the same thing.

**Comment by broerse** [comment]
@sandstrom this 'plus' module work out of the box where in `ember-cli-deploy-build` you can't change the `distDir` in the deploy pipeline we need for [ember-cli-deploy-couchdb](https://github.com/martinic/ember-cli-deploy-couchdb)

See the difference here: https://github.com/martinic/ember-cli-deploy-couchdb#quick-start 

I didn't want to start this addon but was not allowed to change `distDir` see this issue: https://github.com/ember-cli-deploy/ember-cli-deploy-build/pull/23 

So I am willing to merge but it is not going to happen.

**Comment by sandstrom** [comment]
Alright, I understand! Thanks for clarifying!
